/**
 * Central image map. Every portrait on the site is looked up from here, so
 * dropping real photography into public/creators only requires editing the
 * `src` values below — no component changes needed.
 *
 * Placeholders are generated by scripts/generate-placeholder-portraits.mjs
 * (network access to stock-photo hosts is unavailable in this environment).
 */
export interface CreatorPortrait {
  id: string;
  src: string;
  alt: string;
  category?: "Beauty" | "Fashion" | "Lifestyle" | "UGC";
}

export const CREATOR_PORTRAITS: Record<string, CreatorPortrait> = {
  hero: {
    id: "hero",
    src: "/creators/hero.png",
    alt: "Creator walking in a cream shirt and trousers, with two smaller framed shots of other creators filming content behind her",
  },
  atelier1: {
    id: "atelier1",
    src: "/creators/creator-atelier-1.svg",
    alt: "Creator portrait — leather jacket, studio light",
  },
  atelier2: {
    id: "atelier2",
    src: "/creators/creator-atelier-2.svg",
    alt: "Creator portrait — applying lip color, in front of camera",
  },
  atelier3: {
    id: "atelier3",
    src: "/creators/creator-atelier-3.svg",
    alt: "Creator portrait — filming with a handheld camera",
  },
  beauty: {
    id: "beauty",
    src: "/creators/Beauty.png",
    alt: "Beauty creator holding a skincare serum bottle, close-up editorial lighting",
    category: "Beauty",
  },
  lifestyle: {
    id: "lifestyle",
    src: "/creators/Lifestyle.png",
    alt: "Lifestyle creator checking her phone at a café table, natural warm tones",
    category: "Lifestyle",
  },
  fashion: {
    id: "fashion",
    src: "/creators/Fashion.png",
    alt: "Fashion creator walking in an oversized blazer and wide-leg trousers",
    category: "Fashion",
  },
  ugc: {
    id: "ugc",
    src: "/creators/UGC.png",
    alt: "UGC creator holding a product bottle up to a phone on a tripod",
    category: "UGC",
  },
};
