/**
 * Central image map. Every portrait on the site is looked up from here, so
 * dropping real photography into public/creators only requires editing the
 * `src` values below — no component changes needed.
 *
 * Placeholders are generated by scripts/generate-placeholder-portraits.mjs
 * (network access to stock-photo hosts is unavailable in this environment).
 */
export interface CreatorPortrait {
  id: string;
  src: string;
  alt: string;
  category?: "Beauty" | "Fashion" | "Lifestyle" | "UGC";
}

export const CREATOR_PORTRAITS: Record<string, CreatorPortrait> = {
  hero: {
    id: "hero",
    src: "/creators/large.jpg",
    alt: "Creator filming a selfie-style video on a sunlit beach, mountains in the background",
  },
  atelier1: {
    id: "atelier1",
    src: "/creators/creator-atelier-1.svg",
    alt: "Creator portrait — leather jacket, studio light",
  },
  atelier2: {
    id: "atelier2",
    src: "/creators/creator-atelier-2.svg",
    alt: "Creator portrait — applying lip color, in front of camera",
  },
  atelier3: {
    id: "atelier3",
    src: "/creators/creator-atelier-3.svg",
    alt: "Creator portrait — filming with a handheld camera",
  },
  beauty: {
    id: "beauty",
    src: "/creators/creator-beauty.svg",
    alt: "Beauty creator portrait, close-up editorial lighting",
    category: "Beauty",
  },
  lifestyle: {
    id: "lifestyle",
    src: "/creators/creator-lifestyle.svg",
    alt: "Lifestyle creator portrait, natural warm tones",
    category: "Lifestyle",
  },
  fashion: {
    id: "fashion",
    src: "/creators/creator-fashion.svg",
    alt: "Fashion creator portrait, editorial styling",
    category: "Fashion",
  },
  ugc: {
    id: "ugc",
    src: "/creators/creator-ugc.svg",
    alt: "UGC creator portrait, holding a product for camera",
    category: "UGC",
  },
};
